First Microverse Project
AbdimulhinYussuf3675/Hello-Micronaunts pull request #1
Opened 2022-09-20 20:42 UTC by AbdimulhinYussuf3675

2022-09-20 21:16 UTC, GiuseppeTG requested changes
Hi @AbdimulhinYussuf3675  👋 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Alt Text](https://media0.giphy.com/media/wA6aYAO3jH6RmUIBYs/giphy.gif)

## Highlights
✅ Professional Pull Request
✅ No linter errors

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-20 21:23 UTC, GiuseppeTG commented
- [ ] I noticed that you have a professional readme file in your main branch but not in the branch of this Pull Request. Kindly, make sure that your PR has the proper readme file.  :eyes:

![Captura de Pantalla 2022-09-20 a la(s) 4 20 59 p  m](https://user-images.githubusercontent.com/86022690/191366894-04e8dc0f-6b67-4d99-97cb-7364c4f8dbf6.png)

In this case, you can just copy the one you have in your main branch into this branch. For preventing this in future projects you can set up your readme just when you create the new repo, then create your branch from it so that you can have the same readme in both.  🤓 

Keep in mind that in future projects, if you don't have a propper readme file, your submission will be marked as invalid 😮‍💨

2022-09-20 22:23 UTC, jerryowusu requested changes
Hi @AbdimulhinYussuf3675 , 

Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still a few changes to move on to the next project.

![so close](https://user-images.githubusercontent.com/65233860/191375168-9cdc55b5-141e-473b-b7c8-8f5a0ab81f4f.gif)


 ## Highlights

-  All linters are passing :heavy_check_mark: 
- Correct GitHub flow :heavy_check_mark: 
- Nicely arranged files :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-20 22:23 UTC, jerryowusu commented on README.md
> +
Kindly add a detailed description of your project here. For instance you can write: 
`In this project, I set up a "Hello world" repository. No complex coding is required for this exercise. The goal here is to master all of the tools and best practices in setting up a GitHub repository` 
Your description is an extremely important aspect of your project. A well-crafted description allows you to show off your work to other developers as well as potential employers. The quality of a README description often differentiates a good project from a bad project.

2022-09-20 22:23 UTC, jerryowusu commented on README.md
> +
Here you can add instructions on how to set up the project. For instance, you can provide the link for cloning your project, the text editor and browser to be used and how to open or start the project. You can use the image below as a guidance

![Screenshot from 2022-09-20 22-06-16](https://user-images.githubusercontent.com/65233860/191373514-7be98db9-edd0-443f-a7a9-2c476a9c1ba5.png)

2022-09-20 22:23 UTC, jerryowusu commented on README.md
> +This project is [MIT](./LICENSE) licensed.
The link to the license is not working. You can fix this by creating a 'LICENSE' file (in the same location as the 'Readme.md' file), copy [this](https://github.com/jerryowusu/Web-Summit-Accra/blob/main/LICENSE) template into it and edit the year and name accordingly.

2022-09-20 22:23 UTC, jerryowusu commented on README.md
> +👤 **Author1**
Kindly replace your name with 'Author1'

2022-09-21 06:15 UTC, Bondok6 approved these changes
# STATUS: APPROVED :green_circle: :clap: 

## Hi @AbdimulhinYussuf3675 🙋‍♂️, 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

TO HIGHLIGHT:

- Your repo is professional ✅
- Well structured files ✅
- Professional README.md file 💯


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

<img src="https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966" />


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-21 06:19 UTC, merged